name: Release

on:
  workflow_run:
    workflows: [Build & Test]
    branches: master
    types: completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'good-tools/wiregasm' }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        name: lib
        path: built

    - name: Load Dependencies
      run: npm ci

    - name: Load Semantic Release Dependencies
      run: npm install @semantic-release/git -D

    - name: Release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
